export const FETCH_BEERS_REQUEST = "FETCH_BEERS_REQUEST";
export const FETCH_BEERS_FAILURE = "FETCH_BEERS_FAILURE";
export const FETCH_BEERS_SUCCESS = "FETCH_BEERS_SUCCESS";
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const MODIFY_QUANTITY = "MODIFY_QUANTITY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
